name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    name: Audit
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
    - run: go vet ./...
    - run: go test -vet=off ./...
